### ISSUE TITLE
Add guide to setup this repository in local device

### ISSUE THREAD

**Issue by saisab29** [joonshakya/CSIT21#1]
The readme file doesn't include the guide or instructions to setup this repository and how to launch it. It may be difficult for beginners to contribute to this repository
![image](https://github.com/joonshakya/CSIT21/assets/107755209/1073f866-e564-4826-bb23-5f6a1c058f14)

**Comment by joonshakya** [comment]
Sure @saisab29, you can write the documentation for installing packages and running the server and contribute to this repository. It's just pnpm i and pnpm dev (if you are using pnpm). You can clarify and make a PR for everyone to understand.

**Comment by joonshakya** [comment]
Fixed in PR #5
