### ISSUE TITLE
Subject List in front page generator are not displayed based on semester subject

### ISSUE THREAD

**Issue by saisab29** [joonshakya/CSIT21#7]
Every subject is being displayed on each semester list 

To reproduce: 
1. Go to front page generator

3. Every semester have different semester subjects included

Expected behavior: 
The subjects on the front page generator should be based on the current semester

Screenshots: 
![image](https://github.com/joonshakya/CSIT21/assets/107755209/623f4472-6ead-4e0f-b00b-f7b09ed37a7d)
![image](https://github.com/joonshakya/CSIT21/assets/107755209/5335445b-57a9-47c1-9646-f0e813242c57)

**Comment by joonshakya** [comment]
Well, I did that intentionally so that it seems there are lots of things to choose from. Otherwise it looked a bit empty. 😅
